export const TYPES = {
    READ_STATE: "READ_STATE",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ONE_PRODUCT: "REMOVE_ONE_PRODUCT",
    REMOVE_ALL_PRODUCT: "REMOVE_ALL_PRODUCT",
    CLEAR_CART: "CLEAR_CART"






    
}

/******ESTOS SON EJEMPLOS DE LA CLASE DEL CONTADOR
 * ACÁ HAY QUE PONER LAS ACCIONES DE CADA UNO DE NUESTROS COMPONENTES
 * LUEGO EN CADA COMPONENTE IMPORTAMOS LOS TYPES CON 
 * import { TYPES } from "../actions/actions";    ******/