export const TYPES = {
    INCREMENTAR: "INCREMENTAR",
    DECREMENTAR: "DECREMENTAR",
    RESETEAR: "RESETEAR"
}

/******ESTOS SON EJEMPLOS DE LA CLASE DEL CONTADOR
 * ACÁ HAY QUE PONER LAS ACCIONES DE CADA UNO DE NUESTROS COMPONENTES
 * LUEGO EN CADA COMPONENTE IMPORTAMOS LOS TYPES CON 
 * import { TYPES } from "../actions/actions";    ******/